FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      texlive-latex-recommended \
      texlive-pictures \
      texlive-fonts-recommended && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
