#!/usr/bin/env python3
import math
from pathlib import Path
import sys
from typing import Iterable
from xml.sax.saxutils import escape

try:
    import yaml
except ImportError as exc:
    raise SystemExit("PyYAML is required to generate nav2 params.") from exc

from complex_construction_scene import (
    MAP_ORIGIN,
    MAP_RESOLUTION,
    MAP_SIZE,
    MISSION_SEQUENCE,
    START,
    WAYPOINTS,
    BoxObstacle,
    all_obstacles,
    point_in_any_box,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
SIM_DIR = REPO_ROOT / "src" / "my_robot_sim"
NAV_DIR = REPO_ROOT / "src" / "my_robot_navigation"

WORLD_PATH = SIM_DIR / "worlds" / "complex_construction_site.world"
MAP_PGM_PATH = NAV_DIR / "maps" / "complex_construction_map.pgm"
MAP_YAML_PATH = NAV_DIR / "maps" / "complex_construction_map.yaml"
WAYPOINTS_PATH = NAV_DIR / "config" / "waypoints_complex_construction.yaml"
NAV2_PARAMS_PATH = NAV_DIR / "config" / "nav2_params_complex_construction.yaml"


def color_rgba(color) -> str:
    return f"{color[0]:.3f} {color[1]:.3f} {color[2]:.3f} 1"


def box_model(box: BoxObstacle) -> str:
    ambient = color_rgba(box.color)
    diffuse = color_rgba(box.color)
    return f"""    <model name="{escape(box.name)}">
      <static>true</static>
      <pose>{box.cx:.4f} {box.cy:.4f} {0.5 * box.height:.4f} 0 0 {box.yaw:.6f}</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{box.sx:.4f} {box.sy:.4f} {box.height:.4f}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{box.sx:.4f} {box.sy:.4f} {box.height:.4f}</size></box></geometry>
          <material>
            <ambient>{ambient}</ambient>
            <diffuse>{diffuse}</diffuse>
          </material>
        </visual>
      </link>
    </model>
"""


def write_world(path: Path, obstacles: Iterable[BoxObstacle]) -> None:
    floor_w = MAP_SIZE[0] + 0.6
    floor_h = MAP_SIZE[1] + 0.6
    models = "".join(box_model(box) for box in obstacles)
    world = f"""<?xml version="1.0" ?>
<sdf version="1.6">
  <world name="complex_construction_site">
    <gravity>0 0 -9.8</gravity>
    <scene>
      <ambient>0.50 0.50 0.50 1</ambient>
      <background>0.90 0.92 0.94 1</background>
      <shadows>true</shadows>
    </scene>
    <light name="site_sun" type="directional">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.85 0.85 0.82 1</diffuse>
      <specular>0.18 0.18 0.18 1</specular>
      <direction>-0.35 0.20 -1</direction>
    </light>
    <physics type="ode">
      <real_time_update_rate>1000</real_time_update_rate>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <ode>
        <solver><type>quick</type><iters>80</iters></solver>
        <constraints><cfm>0.0</cfm><erp>0.2</erp></constraints>
      </ode>
    </physics>
    <model name="floor">
      <static>true</static>
      <pose>0 0 -0.01 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{floor_w:.3f} {floor_h:.3f} 0.02</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{floor_w:.3f} {floor_h:.3f} 0.02</size></box></geometry>
          <material>
            <ambient>0.54 0.55 0.54 1</ambient>
            <diffuse>0.54 0.55 0.54 1</diffuse>
          </material>
        </visual>
      </link>
    </model>
{models}
  </world>
</sdf>
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(world, encoding="utf-8")


def write_pgm(path: Path, obstacles: Iterable[BoxObstacle]) -> None:
    cols = int(round(MAP_SIZE[0] / MAP_RESOLUTION))
    rows = int(round(MAP_SIZE[1] / MAP_RESOLUTION))
    ox, oy = MAP_ORIGIN
    boxes = list(obstacles)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii") as handle:
        handle.write(f"P2\n# complex_construction_map generated by scripts/generate_complex_construction_assets.py\n")
        handle.write(f"{cols} {rows}\n255\n")
        for row in range(rows):
            y = oy + (rows - row - 0.5) * MAP_RESOLUTION
            values = []
            for col in range(cols):
                x = ox + (col + 0.5) * MAP_RESOLUTION
                values.append("0" if point_in_any_box(x, y, boxes) else "254")
            handle.write(" ".join(values))
            handle.write("\n")


def write_map_yaml(path: Path) -> None:
    data = {
        "image": MAP_PGM_PATH.name,
        "mode": "trinary",
        "resolution": MAP_RESOLUTION,
        "origin": [MAP_ORIGIN[0], MAP_ORIGIN[1], 0.0],
        "negate": 0,
        "occupied_thresh": 0.65,
        "free_thresh": 0.25,
    }
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def write_waypoints(path: Path) -> None:
    lines = ["points:"]
    for name, x, y, yaw in WAYPOINTS:
        lines.append(f"  {name}: {{x: {x:.3f}, y: {y:.3f}, yaw: {yaw:.4f}}}")
    seq = ", ".join(MISSION_SEQUENCE)
    lines.extend(
        [
            "",
            "mission:",
            f"  goal_sequence: [{seq}]",
            "",
            "target_object:",
            "  x: 0.20",
            "  y: 0.30",
            "  z: 0.55",
            "  radius: 0.45",
            "",
            "apriltag_target:",
            "  id: 0",
            "  family: tag36h11",
            "  x: 9.20",
            "  y: 6.50",
            "  z: 1.05",
            f"  approach_x: {WAYPOINTS[-1][1]:.3f}",
            f"  approach_y: {WAYPOINTS[-1][2]:.3f}",
            f"  approach_yaw: {WAYPOINTS[-1][3]:.4f}",
            "  completion_radius: 1.5",
            "",
            "orbit:",
            "  radius: 1.25",
            "  linear_speed: 0.14",
            "  image_center_tolerance: 0.1",
            "  camera_height: 0.43",
            "",
            "safety:",
            "  min_obstacle_distance: 0.45",
            "  warning_obstacle_distance: 0.75",
            "  max_linear_speed: 0.35",
            "  max_angular_speed: 1.2",
            "  max_orbit_radius_error: 0.35",
            "  pan_limit: 3.14159",
            "  tilt_lower_limit: -0.9",
            "  tilt_upper_limit: 0.7",
            "",
            "video:",
            "  fps: 20",
            "  output_dir: ~/ros_videos",
            "",
            "frames:",
            "  target_frame: map",
            "  base_frame: base_link",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def update_nested(data: dict, keys, value) -> None:
    cur = data
    for key in keys[:-1]:
        cur = cur[key]
    cur[keys[-1]] = value


def write_nav2_params(path: Path) -> None:
    source_path = NAV_DIR / "config" / "nav2_params_small_house.yaml"
    with source_path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    update_nested(data, ["amcl", "ros__parameters", "initial_pose", "x"], START[0])
    update_nested(data, ["amcl", "ros__parameters", "initial_pose", "y"], START[1])
    update_nested(data, ["amcl", "ros__parameters", "initial_pose", "yaw"], START[2])
    update_nested(
        data,
        ["controller_server", "ros__parameters", "progress_checker", "movement_time_allowance"],
        75.0,
    )
    update_nested(
        data,
        ["planner_server", "ros__parameters", "GridBased", "tolerance"],
        0.75,
    )
    update_nested(
        data,
        ["global_costmap", "global_costmap", "ros__parameters", "inflation_layer", "inflation_radius"],
        0.35,
    )
    update_nested(
        data,
        ["local_costmap", "local_costmap", "ros__parameters", "inflation_layer", "inflation_radius"],
        0.35,
    )
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def main() -> int:
    obstacles = all_obstacles(include_boundary=True)
    write_world(WORLD_PATH, obstacles)
    write_pgm(MAP_PGM_PATH, obstacles)
    write_map_yaml(MAP_YAML_PATH)
    write_waypoints(WAYPOINTS_PATH)
    write_nav2_params(NAV2_PARAMS_PATH)
    for path in [WORLD_PATH, MAP_PGM_PATH, MAP_YAML_PATH, WAYPOINTS_PATH, NAV2_PARAMS_PATH]:
        print(path.relative_to(REPO_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
